### PR TITLE
Adding Binary Washer/Dryer Status Update

### PR DESCRIPTION
**Pull request by stboch**
In working for the coming Home-Assistant support for Washer/Dryer I needed to fix this module because my dryer uses a binary status update and not the JSON one.

### CODE REVIEW

**Comment by sampsyo** [comment]
Interesting! @boralyl, can you please confirm that your devices produce JSON status messages? If so, we will need to find some way to simultaneously support both JSON and binary status data, perhaps by detecting the kind of data (i.e., by trying to decode with JSON, and if that fails, falling back to binary decoding).

**Comment by boralyl** [comment]
I'll double check this weekend and let you know.

**Comment by boralyl** [comment]
I modified example.py to use poll_json and can confirm that for both my washer and dryer I do in fact need to use the binary status data.

**Comment by sampsyo** [comment]
OK; cool! I'll merge this now then.

**Comment by stboch** [comment]
The function decode_monitor supports both the json and binary so it should be fine for both. Glad it worked. 

@boralyl  I will hopefully today post the washer/dryer mod's to the sensors.py it doesn't seem like the there is many attributes defined for the washer can you send me a snip of your example.py mon of the washer.

**Pull request merged**
