### PR TITLE
Fixes the ReferenceValue type.

### PR DESCRIPTION
**Pull request by boralyl**
This type is a reference to another key at the root of the data.  Prior to this PR we were just storing the name and not the value that the reference pointed to.

Also renamed the the `test_simple.py` file to `test_core.py`.

### CODE REVIEW

**Comment by sampsyo** [comment]
Nice! This looks perfect.

**Comment by sampsyo** [comment]
BTW, I'd be happy to make you a collaborator on this repository so you can merge your own PRs! Still happy to offer code reviews, of course.

**Comment by boralyl** [comment]
> BTW, I'd be happy to make you a collaborator on this repository so you can merge your own PRs! Still happy to offer code reviews, of course.

Sure, that would make it easier for small PRs like this.  I'll still put up PRs for code review that are more substantial for feedback.

**Comment by sampsyo** [comment]
Awesome! Invitation sent. And thanks for all the contributions!

**Pull request merged**
