### PR TITLE
Fix ENERGY_SAVING typo.

### PR DESCRIPTION
**Pull request by dmcc**
Without this, I get exceptions when using this from Home Assistant.

### CODE REVIEW

**Comment by sampsyo** [comment]
Interesting—perhaps this is a difference between your and my AC product models? Any chance you could share your `wideq_state.json`? A redacted version—I'm interested in the `model_info` data, which lists settings like this. In mine, the `OpMode` entry looks like this:

```json
"OpMode": {
    "_comment": "Control_\uc6b4\uc804\ubaa8\ub4dc",
    "type": "Enum",
    "default": "0",
    "option": {
        "0": "@AC_MAIN_OPERATION_MODE_COOL_W",
        "1": "@AC_MAIN_OPERATION_MODE_DRY_W",
        "2": "@AC_MAIN_OPERATION_MODE_FAN_W",
        "3": "@AC_MAIN_OPERATION_MODE_AI_W",
        "4": "@AC_MAIN_OPERATION_MODE_HEAT_W",
        "5": "@AC_MAIN_OPERATION_MODE_AIRCLEAN_W",
        "6": "@AC_MAIN_OPERATION_MODE_ACO_W",
        "7": "@AC_MAIN_OPERATION_MODE_AROMA_W",
        "8": "@AC_MAIN_OPERATION_MODE_ENERGY_SAVING_W",
        "23": "@AC_MAIN_OPERATION_MODE_ANTIBUGS_W"
    }
},
```

**Comment by dmcc** [comment]
My `model_info` is just an empty dictionary, it seems:

    ...
    "model_info": {}
    ...

Do you think it would help if I rerun `example.py`?

In case it helps: my AC unit is an LW1217ERSM.

**Comment by sampsyo** [comment]
Ah, yes, definitely. You can first run `python3 example.py` by itself to get a list of your devices, then use `python3 example.py ac-mon ID` (supplying an ID string) to try monitoring a specific device. That should fetch the model info.

**Comment by dmcc** [comment]
Sure, here's the `OpMode` section: (LMK if other sections would be useful too)

`"OpMode": {"_comment": "Control_\uc6b4\uc804\ubaa8\ub4dc", "type": "Enum", "default": "0", "option": {"0": "@AC_MAIN_OPERATION_MODE_COOL_W", "1": "@AC_MAIN_OPERATION_MODE_DRY_W", "2": "@AC_MAIN_OPERATION_MODE_FAN_W", "3": "@AC_MAIN_OPERATION_MODE_AI_W", "4": "@AC_MAIN_OPERATION_MODE_HEAT_W", "5": "@AC_MAIN_OPERATION_MODE_AIRCLEAN_W", "6": "@AC_MAIN_OPERATION_MODE_ACO_W", "7": "@AC_MAIN_OPERATION_MODE_AROMA_W", "8": "@AC_MAIN_OPERATION_MODE_ENERGY_SAVER_W"}}`

**Comment by sampsyo** [comment]
Interesting. It looks like it is indeed different for your device.

Perhaps the right solution here, then, would be to somehow avoid hard-coding those strings and to instead read them from the model description info. Or to somehow allow either of the two strings, depending on the contents of the `OpMode` map for the model. Tricky!

**Comment by dmcc** [comment]
I think this is a duplicate issue of #18 (which seems to be fixed), so closing this.

**Pull request closed without merging**
