### PR TITLE
Update ac.py

### PR DESCRIPTION
**Pull request by ctih**
Changed to AUTO mode the WIND mode does not work in HA now

### CODE REVIEW

**Comment by sampsyo** [comment]
Hmm... I don’t think we want to have two things called AUTO in this enum. I guess it seems like some models use this and some use the setting called “auto”?

Can we call this option NATURE, please? Then, in https://github.com/sampsyo/hass-smartthinq/pull/25, we can use one setting or the other.

**Comment by ctih** [comment]
No problem

I was also wanting to call it NATURE but this mode does not exist in enum? does Nature mode need to be added to home assistant code?

**Comment by ctih** [comment]
NATURE is not on this list. 

# Possible fan state
FAN_ON = "on"
FAN_OFF = "off"
FAN_AUTO = "auto"
FAN_LOW = "low"
FAN_MEDIUM = "medium"
FAN_HIGH = "high"
FAN_MIDDLE = "middle"
FAN_FOCUS = "focus"
FAN_DIFFUSE = "diffuse"

[https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/climate/const.py](url)

**Comment by sampsyo** [comment]
Indeed. To clarify an architectural thing, the wideq library is supposed to faithfully represent the underlying data in a useful but abstract way. It should not need to be tied to the choices or limitations of Home Assistant (or any other software it might support).

So I think what we'll have to do here is something more complicated in the Home Assistant add-on. For example, one option is to detect whether the device supports the "NATURE" mode and, *only* if so, map it to one of of Home Assistant's built-in fan mode options. Another would be to pick a fan mode (not "auto") that most closely matches that setting and use that. Yet another would be to detect unsupported fan modes and map them all to "auto." But regardless, the complex handling should go there.

**Comment by ctih** [comment]
I agree

**Comment by fabiomsouto** [comment]
Hey,

I agree with @sampsyo on this one, so as a first stage let's merge this in and then we can handle the device state in the hass component :)

**Comment by adrianrdzv** [comment]
Hello. I'm currently having the following error in the hass component:
```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 408, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 273, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 314, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 238, in state_attributes
    data[ATTR_FAN_MODE] = self.fan_mode
  File "/config/custom_components/smartthinq/climate.py", line 193, in fan_mode
    return FAN_MODES[mode.name]
KeyError: 'NATURE'
```
I guess is related to the introduction of this enum value?

**Pull request merged**
