### PR TITLE
Moves wideq.py into a it's own module.

### PR DESCRIPTION
**Pull request by boralyl**
This will make it easier to break up the wideq.py file into separate python files instead of having one large file.  e.g. something like device.py, ac.py, washer.py, dryer.py, etc.

Also added a basic test and required files to run them.

### CODE REVIEW

**Comment by sampsyo** [comment]
Looks cool; thanks! This would be good to do. However, there are a couple of odd things here:

- Looks like a bunch of unrelated commits somehow got wrapped up in this PR. Not entirely sure why? It might be easiest to squash these changes to focus on what's actually changed.
- Can we leave the testing stuff to its own PR? Tests would be great, but we can think specifically about how we want to do them.

**Comment by boralyl** [comment]
Yeah, I think it's because I forked from a different fork of your repo and since I already have a fork it won't allow me to re-fork from your repository.

**Comment by sampsyo** [comment]
Hmm… I think it should be possible to pull my `master` into your fork (under a different name) and open a PR from there.

**Comment by boralyl** [comment]
I deleted my fork and re-forked.  I'll re-open there.

**Pull request closed without merging**
